services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
